config/routes.rb
Rails.application.routes.draw do
  root "pins#index"
  get '/pins/new', to: 'pins#new', as: 'new_pin'
  post '/pins', to: 'pins#create'
  get '/pins/:id', to: 'pins#show', as: 'pin'
  get '/pins/:id/edit', to: 'pins#edit', as: 'edit_pin'
  delete '/pins/:id', to: 'pins#destroy'
  resources :pins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    def index
        @pins = Pin.all
    end

    def new
        @pin = Pin.new
    end

    def create
        pin = Pin.new(pin_params) 
        pin.user = current_user

        if pin.save
            redirect_to root_path
        else 
            render :new
        end
    end

    def show 
        pin = Pin.find(params[:id])
    end

    def edit 
        pin = Pin.find(params[:id])
    end

    def update 
        @pin = Pin.find(params[:id])
        if @pin.update(pin_params)
            redirect_to pins_path, notice: "actualizado"
        end
    end

    def destroy 
        pin = Pin.find(params[:id])
        pin.destroy

        redirect_to pins_path, notice: "elimnado"
    end

    private 
        def pin_params
            params.require(:pin).permit(:title, :image_url, :id)
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PintApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">PintApp</a>

      <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
        <ul class="navbar-nav">
          <% if signed_in? %>
            <li class="mr-4"> <%= link_to "Nuevo Pin", new_pin_path %> </li>
            <li> <%= link_to "Salir", destroy_user_session_path, method: :delete%> </li>
          <% else %>
            <li class="mr-4"> <%= link_to "Registrate", new_user_registration_path %> </li>
            <li> <%= link_to "Iniciar sesión", new_user_session_path %> </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pins/index.html.erb
<section id="pins" class="transitions-enabled clearfix">
    <% @pins.each do |pin| %>
        <div class="d-inline-block mt-3 mb-3">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-6 col-md-8 ml-5">
                    <div class="card">
                        <div
                            title="Something"
                            class="cover cover-sm mt-3"
                            style="background-image:url(<%= pin.image_url %>" 
                        >
                        </div>

                        <div class="card-body">
                            <h2 class="card-title" ><%= pin.title %></h2>
                            <p class="card-text"> Publicado por <%= pin.user.email %> </p>
                            <p> <%= link_to "Eliminar", pin, method: :delete, data:{confirm: "Are you sure?"} %></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</section>

app/views/pins/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-sm-6 col-sm-4 col-sm-offset-3">
            <h1 class="text-center"> New Pin</h1>
            <%= form_for @pin do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>

                 <div class="form-group">
                    <%= f.label :image_url %>
                    <%= f.url_field :image_url, class: "form-control" %>
                </div>

                <div>
                    <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>